pool:                                                                            
  vmImage: 'ubuntu-latest'
  
variables:
  sapphire_commit: fb4b8d2

name: $(sapphire_commit)-$(Rev:r)
steps:
- task: CmdLine@2                                                                
  displayName: Docker build                                                      
  inputs:                                                                        
    script: docker build --build-arg CHECKOUT=$(sapphire_commit) -t bnvi/sapphire:$(Build.BuildNumber) . 

- task: Docker@2
  condition: succeeded()
  displayName: Docker push
  inputs:
    containerRegistry: dockerhub
    command: push
    repository: bnvi/sapphire
    tags: $(Build.BuildNumber)