pool:                                                                            
  vmImage: 'ubuntu-latest'                                                       
                                                                                  
steps:                                                                           
- task: CmdLine@2                                                                
  displayName: Docker build                                                      
  inputs:                                                                        
    script: docker build -t bnvi/sapphire:$(Build.SourceBranchName) . 

- task: Docker@2
  condition: succeeded()
  displayName: Docker push
  inputs:
    containerRegistry: dockerhub
    command: push
    repository: bnvi/sapphire
    tags: $(Build.SourceBranchName)
